network_literal_prefix = "NL_"
port_literal_prefix = "PL_"
separator_character = "‽"
literal_objects_description = "Originally a literal value, converted to object."
virtual_object_container_name = "virtual_object_container"